title: code-victor-now
author: code-victor-now
email: vcalesco@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  code-victor-now
  
  
# social links

github_username:  code-victor-now

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
